// Generated by scripts/generate-audio-manifest.mjs.
// Do not edit by hand; keep audio filenames unchanged and rerun the script.

export const GENERATED_TRACK_LIBRARY = [
  {
    "trackId": "track_01",
    "label": "Boing",
    "url": "/audio/boing.mp3"
  },
  {
    "trackId": "track_02",
    "label": "Womp Womp",
    "url": "/audio/womp-womp.mp3"
  }
] as const;
